### ISSUE TITLE
Add documentation for Helix integration

### ISSUE THREAD

**Issue by Yappaholic** [uros-5/htmx-lsp2#3]
On the page there are videos including functionality inside Helix, but there is no provided configuration to enable it properly. Right now I can launch htmx-lsp with helix, but it does nothing.
My config looks like that:
```toml
htmx = {command = "/home/savvy/.cargo/bin/htmx-lsp2"}
```

**Comment by uros-5** [comment]
```toml
[language-server.htmx-lsp]
command = "htmx-lsp2"
config = { lang = "rust", template_ext = "jinja", templates = ["./your_templates_dir"], js_tags = ["your_js_dir"], backend_tags = ["your_backend_dirs", "./server", "./models"] }
timeout = 5

[[language]]
name = "html"
language-servers = [ "htmx-lsp"]
```

**Comment by Yappaholic** [comment]
Trying to make it work for Golang with templ but still no do
```toml
[language-server.htmx-lsp]
command = "htmx-lsp2"
config = { lang = "go", template_ext = "templ", templates = ["views", "./views"] }
timeout = 5
```

**Comment by uros-5** [comment]
`backend_tags` and `js_tags` are missing in configuration.
You can set it to empty array.

**Comment by Yappaholic** [comment]
> You can set it to empty array.

I did it and it now works! Big thanks to you!

If you don't mind, I can try and make a pull request with the helix setup in README file.

**Comment by Smithx10** [comment]
I'm attempting to use this in a project using Golang and Templ.  What are the required values for templates etc?

**Comment by Yappaholic** [comment]
> I'm attempting to use this in a project using Golang and Templ. What are the required values for templates etc?

You can try with this if you use Helix:
```toml
[language-server.htmx-lsp]
command = "htmx-lsp2"
config = { lang = "go", template_ext = "templ", templates = ["views", "./views"] , backend_tags = [""], js_tags = [""]}
timeout = 5
```
